apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: default
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryacm8754.azurecr.io/trips:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_DBNAME
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_USER
        - name: OPENAPI_DOCS_URI
          value: http://trips/swagger/v1/swagger.json
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP