apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: default
spec:
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryacm8754.azurecr.io/userprofile:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # the application listens to this port
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_DBNAME
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlconnectioninfo
              key: SQL_USER
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    app: userprofile
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP